### ISSUE TITLE
There is a flaw in this module

### ISSUE THREAD

**Issue by andreGarvin** [miguelmota/is-boolean#2]
Hey, I was looking around in my `node_modules` folder and I came across yours.

I looked at the code and there is a flaw in checking the weather is something is a boolean/ type of boolean or not.

the way you are doing it is like this, `Object.prototype.toString.call(v) === '[Object boolean]'`. This is a broken because someone can easily do this
```js
global.Object.prototype.toString = function(s) {
return '[Object boolean]';
}
```
which means that I could potentially declare anything as a type of booean when it is not.

A better way of checking is a boolean is by doing this

```js
function isBoolean(v) {
return v === false || v === true;
}
```
@miguelmota

**Comment by miguelmota** [comment]
@andreGarvin 

great suggestion, module is updated. Thanks for reporting!
